services:
  postgres:
    container_name: roombook_db
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: roombook_db
      POSTGRES_USER: roombook_user
      POSTGRES_PASSWORD: roombook_pw
    ports:
      - 5432:5432
  app:
    container_name: roombook_app
    image: roombook_app:latest
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/roombook_db

