services:
  postgres:
    container_name: roombook_db
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: roombook_db
      POSTGRES_USER: roombook_user
      POSTGRES_PASSWORD: roombook_pw
    ports:
      - 5432:5432
